### ISSUE TITLE
Add support for shared libraries dependencies in remote modules

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKPythonPackage#165] opened 2021-09-30 02:48 UTC
We want to package the OpenCL ICD loader in particular in dependent remote modules.

We can build on the shared library support in 5.3rc1 for TBB.

For the platform-specific wheel fix-up tools, auditwheel (Linux), delocate (macOS), delvewheel (Windows) we need to add support for additional shared libraries. Mostly, this should be making the scripts that expose the path to local libraries with environmental variables allow appending to that variable, then set this variable to the path to the OpenCL ICD loader library in the remote module GitHub CI configuration.

E.g.:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/ad3f8d0c3dcb0e1b959924b4ceea8e832d612758/scripts/internal/manylinux-build-module-wheels.sh#L14

-> 

```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/work/oneTBB-prefix/lib64
````

For Windows:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/ad3f8d0c3dcb0e1b959924b4ceea8e832d612758/scripts/windows_build_wheels.py#L225-L228

We may need to change this script to enable passing addition paths as a CLI argument. Also, we will likely need to adjust the strategy since delvewheel patches `itk/__init__.py`.

For macOS:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/ad3f8d0c3dcb0e1b959924b4ceea8e832d612758/scripts/macpython-build-module-wheels.sh#L29

**Comment by thewtex** [comment] 2021-10-02 17:15
> the OpenCL ICD loader as a third-party module to ITK 

No

> Revisiting this, I think I understand that we want to limit changes so that they support remote modules without changes to ITK.

Correct. The only changes required are the changes in this repository in the three locations noted.

**Comment by tbirdso** [comment] 2021-10-04 13:33
Also note that attempting to configure and build `ITKPythonPackage` with CMake successfully builds the `oneTBB` target but configuring the `ITK` target fails:
> CMake Error at Modules/ThirdParty/TBB/itk-module-init.cmake:1 (find_package):
  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

 > Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMake/ITKModuleEnablement.cmake:338 (include)
  CMakeLists.txt:525 (include)


> -- Configuring incomplete, errors occurred!

**Comment by thewtex** [comment] 2021-10-04 14:41
> dockcross-manylinux-download-cache-and-build-module-wheels.sh per the docs fails with the message
> cp: cannot stat 'ITKPythonPackage/oneTBB-prefix': No such file or directory

TBB is only available in ITK 5.3, so try:

```
export ITK_PACKAGE_VERSION=v5.3rc01
```

Note that the default value in the script is older.

**Comment by thewtex** [comment] 2021-10-04 14:42
> Also note that attempting to configure and build ITKPythonPackage

What are the commands used here?

**Comment by tbirdso** [comment] 2021-10-04 14:53
> TBB is only available in ITK 5.3, so try:

Thanks, I'll give this a shot

> > Also note that attempting to configure and build ITKPythonPackage

> What are the commands used here?

This was in relation to attempting to manually build ITKPythonPackage so as to fetch and build the `oneTBB-prefix` source, aka `cmake ITKPythonPackage ITKPythonPackage/build` and `cmake --build ITKPythonPackage/build`. 

Since the `oneTBB-prefix` source is generated before the `ITK` build fails here I was able to move the folder up to `ITKPythonPackage/oneTBB-prefix` and the dockcross script passes the step of getting this folder. However it then fails later when trying to get Doxygen sources:

> curl https://data.kitware.com/api/v1/file/5c0aa4b18d777f2179dd0a71/download -o doxygen-1.8.11.linux.bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

> curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

However, running `curl https://data.kitware.com/api/v1/file/5c0aa4b18d777f2179dd0a71/download -o doxygen-1.8.11.linux.bin.tar.gz` on the command line succeeds, so I don't think this is actually an issue with any Girder certificates?

**Comment by tbirdso** [comment] 2021-10-04 15:22
On the Windows side I can build a remote module (currently using `ITKVkFFTBackend` for testing purposes since we know it requires shared libraries) but cleanup fails to remove Vulkan remote module Git archive while in Powershell Administrator mode and exits early:
> error: [WinError 5] Access is denied: '_skbuild\\win-amd64-3.6\\cmake-build\\_deps\\vulkan_lib-src\\.git\\objects\\pack\\pack-1c34d8537eccbb71559a700c0fae9132845e3368.idx'
Traceback (most recent call last):
  File "C:\P\IPP\scripts\windows_build_module_wheels.py", line 71, in <module>
    build_wheels(cleanup=args.cleanup, py_envs=args.py_envs, cmake_options=args.cmake_options)
  File "C:\P\IPP\scripts\windows_build_module_wheels.py", line 61, in build_wheels
    check_call([python_executable, "setup.py", "clean"])
  File "C:\Python37-x64\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\P\\IPP\\venv-36-x64\\Scripts\\python.exe', 'setup.py', 'clean']' returned non-zero exit status 1.

Cleanup is the last step in `windows_build_module_wheels.py` so I'm not sure if it's a major issue? Library files are generated in `lib/itk`.

**Comment by tbirdso** [comment] 2021-10-04 15:25
Fixing the ITK version with `export ITK_PACKAGE_VERSION=v5.3rc01` in Ubuntu still fails to get oneTBB-prefix` as it is not present/fetched in ITKPythonPackage:

> cp: cannot stat 'ITKPythonPackage/oneTBB-prefix': No such file or directory

The script is able to continue past this error but still fails on the Doxygen SSL certificate problem:
> ++ curl https://data.kitware.com/api/v1/file/5c0aa4b18d777f2179dd0a71/download -o doxygen-1.8.11.linux.bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

**Comment by tbirdso** [comment] 2021-10-04 18:29
For future reference it appears that `oneTBB-prefix` is found in the [ITKPythonBuild v5.3rc01 tarball](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc01) under `ITKPythonPackage/ITK-source` rather than `ITKPythonPackage`

**Comment by SimonRit** [comment] 2021-10-04 21:29
> ++ curl https://data.kitware.com/api/v1/file/5c0aa4b18d777f2179dd0a71/download -o doxygen-1.8.11.linux.bin.tar.gz
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> curl: (60) SSL certificate problem: certificate has expired
> More details here: https://curl.haxx.se/docs/sslcerts.html

For your information, this SSL issue is also a problem in ITK remote modules, e.g. in [RTK](https://github.com/SimonRit/RTK/runs/3791977454) or [TubeTK](https://github.com/InsightSoftwareConsortium/ITKTubeTK/runs/3796462118). Unfortunately, I don't know how to solve it! I tried [this](https://github.com/SimonRit/RTK/pull/440/commits/34c355510c56611c318f82efdc83be52209a8c4f) but it does not work...

**Comment by thewtex** [comment] 2021-10-05 03:43
> curl: (60) SSL certificate problem: certificate has expired

This may be caused by:

https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

We could try adding:

```
sudo apt-get update
sudo apt-get install -y ca-certificates
```

**Comment by SimonRit** [comment] 2021-10-05 08:16
> We could try adding:
> 
> ```
> sudo apt-get update
> sudo apt-get install -y ca-certificates
> ```

Thanks @thewtex. I tried and it did not work: https://github.com/SimonRit/RTK/runs/3800029186?check_suite_focus=true
I also tried using `dpkg-reconfigure` but same problem: https://github.com/SimonRit/RTK/runs/3800150833
After a closer look, I think the problem is in the manylinux docker and should be fixed in `ITKPythonBuilds-linux.tar.zst`. I'll open an issue on ITK/ITKPythonPackage for keeping track of this issue.

**Comment by tbirdso** [comment] 2021-10-05 12:38
Thank you for tracking this @SimonRit !

After switching to ITK v5.3rc01 (`export ITK_PACKAGE_VERSION="v5.3rc01"`) per @thewtex 's suggestion I stopped seeing the SSL issue yesterday and the build was able to proceed through [`internal/manylinux-build-common.sh`](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/internal/manylinux-build-common.sh) without failure. Maybe it has already been fixed?

As you said, the issue is in the docker container and I had no trouble fetching the Doxygen resources locally.

**Closed** 2021-10-13 13:09 UTC
